<?php

/**
 * @file
 * This file demonstrates how to use hook functions
 */


 /**
  * Implements hook_cron().
  */
function mymodule_cron() {
    \Drupal::messenger()->addMessage(t("Hello from mymodule cron :) :)"));
}

/**
 * Implements hook_form_alter().
 */
function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    # the form id in the HTML document is node-article-edit-form but you should use underscore node_article_edit_form
    # that is the behavior of the Drupal.
    // prints form id => \Drupal::messenger()->addMessage($form_id);
    if ($form_id === 'node_article_edit_form') {
        $form['actions']['submit']['#value'] = t("Save this awesome article");
    }
}